Repository jenkins-x-labs/helmboot, pull requests merged in 2020-03, with the labels that each got.

#8 fix: disable secret env var validation
  go.mod
  go.sum
  pkg/cmd/create/create.go
Labels: size/XS

#9 fix: output the git URL and use the correct CLI binary
  pkg/envfactory/env_factory.go
  pkg/secretmgr/factory/resolver.go
Labels: size/S

#10 fix: add a CLI argument to enable multi cluster
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/envfactory/env_factory.go
Labels: approved, size/M

#13 fix: reuse same git logic for verify as create
  pkg/cmd/verify/verify.go
  pkg/envfactory/env_factory.go
Labels: size/M

#15 fix: upgrade jx
  go.mod
  go.sum
Labels: approved, size/XS

#17 fix: auto detect git kind correctly on boot + detect project not found correctly
  pkg/envfactory/repo_factory.go
Labels: approved, ok-to-test, size/S

#20 fix: improvements to git and use jxl-boot chart
  go.mod
  pkg/cmd/create/create.go
  pkg/cmd/run/run.go
  pkg/cmd/upgrade/upgrade.go
  pkg/cmd/verify/requirements/verify_requirements.go
  pkg/envfactory/repo_factory.go
  pkg/gitconfig/config_setup.go
  pkg/helmer/constants.go
  pkg/helmer/helm.go
  pkg/helmer/helm_cli.go
  pkg/helmer/helm_cli_test.go
  pkg/helmer/helpers.go
  pkg/helmer/interface.go
  pkg/reqhelpers/helpers.go
Labels: approved, size/XXL

#21 fix: avoid the oauth login with batch mode
  pkg/jxadapt/helpers.go
Labels: size/S

#22 fix: add update of helm repos before starting the job
  pkg/cmd/run/run.go
Labels: size/XS

#25 fix: improvements
  pkg/cmd/run/run.go
Labels: size/XS

#26 fix: support private git repositories
  pkg/cmd/run/run.go
Labels: size/M

#27 fix: don't terminate if we can't extract the user/token
  pkg/cmd/run/run.go
Labels: size/S

#28 fix: use the namespace from the requirements for setting up local secrets
  go.mod
  go.sum
  pkg/cmd/run/run.go
  pkg/secretmgr/factory/factory.go
  pkg/secretmgr/local/local_secretmgr.go
Labels: approved, lgtm, size/M

#29 fix: add verify of secrets
  pkg/cmd/create/create.go
  pkg/cmd/run/run.go
  pkg/cmd/secrets/secrets.go
  pkg/cmd/secrets/secrets_export.go
  pkg/cmd/secrets/secrets_import.go
  pkg/cmd/secrets/secrets_test.go
  pkg/cmd/secrets/secrets_verify.go
  pkg/cmd/step/step_status.go
  pkg/secretmgr/factory/resolver.go
  pkg/secretmgr/helpers.go
Labels: approved, size/L

#30 fix: improve CLI handling
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/upgrade/upgrade.go
  pkg/envfactory/env_factory.go
  pkg/jxadapt/helpers.go
  pkg/reqhelpers/flags.go
  pkg/reqhelpers/helpers.go
Labels: approved, size/L

#31 fix: default to private git repositories
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/upgrade/upgrade.go
  pkg/envfactory/env_factory.go
  pkg/envfactory/repo_factory.go
Labels: approved, size/S

#32 fix: upgrade jx
  go.mod
  go.sum
Labels: size/XS

#33 fix: add support for the acme app
  pkg/cmd/create/create_test.go
  pkg/reqhelpers/helpers.go
Labels: approved, size/XS

#34 fix: add support for ingress kind and service flags
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/verify/requirements/verify_requirements.go
  pkg/reqhelpers/flags.go
  pkg/reqhelpers/helpers.go
Labels: size/M

#35 chore: bump github cli so we use the latest callback URL for the gith…
  go.mod
  go.sum
Labels: size/XS

#36 fix: lets add extra options when running the boot job
  go.mod
  pkg/reqhelpers/helpers.go
Labels: size/S

#38 fix: avoid eager creation of dev Environment
  go.mod
  go.sum
  pkg/cmd/run/run.go
Labels: approved, size/M

#39 fix: add the destroy command
  go.mod
  go.sum
  pkg/cmd/destroy/destroy.go
  pkg/cmd/root.go
  pkg/cmd/run/run.go
  pkg/cmd/verify/requirements/verify_requirements.go
  pkg/githelpers/helpers.go
  pkg/reqhelpers/helpers.go
Labels: approved, size/L

#40 fix: better git URL handling for destroy
  pkg/cmd/destroy/destroy.go
Labels: approved, size/S

#41 fix: default docker registry on k8s provider
  go.mod
  go.sum
  pkg/cmd/create/create_test.go
  pkg/reqhelpers/helpers.go
Labels: size/S

#43 feat: add helper message to configure install on boot
  go.mod
  pkg/envfactory/env_factory.go
Labels: approved, lgtm, size/XS

#42 fix: use the right chart name for external-dns
  pkg/cmd/create/create_test.go
  pkg/reqhelpers/helpers.go
Labels: size/XS
